# Generated by Django 4.0.3 on 2022-03-19 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cik_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='EbitdaFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('ebitda', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='core_compan_name_f8e523_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='core_compan_slug_9ea5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['cik_number'], name='core_compan_cik_num_ffc44c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('slug', 'cik_number')},
        ),
        migrations.AlterUniqueTogether(
            name='revenuefiling',
            unique_together={('company', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='ebitdafiling',
            unique_together={('company', 'start_timestamp', 'end_timestamp')},
        ),
    ]
