# Generated by Django 4.0.3 on 2022-03-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ebitdafiling'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ebitdafiling',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ebitdafiling',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ebitdafiling',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ebitdafiling',
            unique_together={('company', 'start_timestamp', 'end_timestamp')},
        ),
        migrations.RemoveField(
            model_name='ebitdafiling',
            name='timestamp',
        ),
    ]
